import type { Metadata } from "next";
// import { ThemeProvider } from "@/component/theme-provider";
import { ReactNode } from "react";






export const metadata: Metadata = {
  title: "Portfolio - Shree",
  description: "Generated by create next app",
};


// app/layout.tsx


export default function RootLayout({ }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider> */}
      </body>
    </html>
  )
}
